CRYOPOSE_POSITION_X = "x"
CRYOPOSE_POSITION_Y = "y"
CRYOPOSE_POSITION_Z = "z"

CRYOPOSE_ORIENTATION = "orientation"

CRYOPOSE_EXPERIMENT_ID = "experiment_id"

CRYOPOSE_PIXEL_SPACING = "pixel_spacing"
